var g_CityDiv = null;
function setInputValue(strTxtID,strTxt)
{
	document.getElementById(strTxtID).value = strTxt;
	document.getElementById("mapFrame").contentWindow.setMapCenter(strTxt);
	noCityDiv();
}

function noCityDiv()
{
	g_CityDiv.style.display="none";
	document.body.removeChild(g_CityDiv);
	g_CityDiv = null;
}


function getInputBoxPos(strTxtID){
  var arPos = null;
  var txtInput = document.getElementById(strTxtID);
  if( txtInput == null ) return null;
  
  arPos = new Array();
  arPos[0] = txtInput["offsetLeft"];
  arPos[1] = txtInput["offsetTop"];
  arPos[2] = txtInput["offsetWidth"];
  arPos[3] = txtInput["offsetHeight"] * 2;

  return arPos;
}

function showCityDiv(strTxtID)
{
	if(g_CityDiv!=null) return;
	var txtInputPos = getInputBoxPos(strTxtID);
	g_CityDiv = document.createElement("DIV");
	g_CityDiv.id = "cityDiv";
	g_CityDiv.style.borderRight="black 1px solid";
	g_CityDiv.style.borderLeft="black 1px solid";
	g_CityDiv.style.borderTop="black 1px solid";
	g_CityDiv.style.borderBottom="black 1px solid";
	g_CityDiv.style.zIndex="100";
	g_CityDiv.style.paddingRight="0px";
	g_CityDiv.style.paddingLeft="5px";
	g_CityDiv.style.paddingTop="5px";
	g_CityDiv.style.paddingBottom="5px";
	g_CityDiv.style.display="block";
	g_CityDiv.style.position="absolute";
	g_CityDiv.style.backgroundColor="#ffffff";
	
	g_CityDiv.style.left=txtInputPos[0] + "px";
	g_CityDiv.style.top=txtInputPos[1] + txtInputPos[3] + "px";
	//alert(g_CityDiv.style.top);
	createCityDIVHtml(strTxtID);
	document.body.appendChild(g_CityDiv);
}

function createCityDIVHtml(strTxtID)
{
	var strHtml = "<iframe style=\"position:absolute;z-index:-1;width:425px;height:500px;\" frameborder=\"0\"></iframe><div style=\"overflow:auto;width:425px;height:500px;\"><table width=\"395\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"  bgcolor=\"#FFFFFF\" class=\"right_box\" style=\"padding:0 10px;\" >\r\n";
	strHtml += "<tr><td width=\"360\" height=\"27\" class=\"t_b\"><strong>省市列表</strong></td>";
	strHtml += "<td width=\"38\" align=\"right\" valign=\"middle\" class=\"t_b\"><a onclick=\"noCityDiv();\"><img src=\"../images/closebtn.gif\" width=\"11\" height=\"11\" border=\"0\" /></a></td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\">全国</span>(以下含34个省、自治区、直辖市、特别行政区，340个地级市；拼音排序) </td></tr>\r\n";
	//下面的就是真正的全国的内容了 
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>A</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阿拉善盟');\">阿拉善</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','鞍山市');\">鞍山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','安庆市');\">安庆</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','安阳市');\">安阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阿坝藏族羌族自治州');\">阿坝</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','安顺市');\">安顺</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阿里地区');\">阿里</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','安康市');\">安康</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阿克苏地区');\">阿克苏</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阿勒泰地区');\">阿勒泰</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阿拉尔市');\">阿拉尔</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','澳门特别行政区');\">澳门</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>B</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','北京市');\">北京</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','保定市');\">保定</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','包头市');\">包头</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','本溪市');\">本溪</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','白山市');\">白山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','白城市');\">白城</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','蚌埠市');\">蚌埠</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','亳州市');\">亳州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','滨州市');\">滨州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','北海市');\">北海</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','百色市');\">百色</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','白沙黎族自治县');\">白沙</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','保亭黎族苗族自治县');\">保亭</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','巴中市');\">巴中</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','毕节地区');\">毕节</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','保山市');\">保山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宝鸡市');\">宝鸡</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','白银市');\">白银</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','博尔塔拉蒙古自治州');\">博尔塔拉</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','巴音郭楞蒙古自治州');\">巴音郭楞</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>C</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','承德市');\">承德</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','沧州市');\">沧州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','长治市');\">长治</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','赤峰市');\">赤峰</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','朝阳市');\">朝阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','长春市');\">长春</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','常州市');\">常州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','滁州市');\">滁州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','池州市');\">池州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','长沙市');\">长沙</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','常德市');\">常德</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','郴州市');\">郴州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','潮州市');\">潮州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','崇左市');\">崇左</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','澄迈县');\">澄迈</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','昌江黎族自治县');\">昌江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','重庆市');\">重庆</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','成都市');\">成都</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','楚雄彝族自治州');\">楚雄</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','昌都地区');\">昌都</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','昌吉回族自治州');\">昌吉</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>D</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','大同市');\">大同</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','大连市');\">大连</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','丹东市');\">丹东</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','大庆市');\">大庆</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','大兴安岭地区');\">大兴安岭</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','东营市');\">东营</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','德州市');\">德州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','东莞市');\">东莞</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','儋州市');\">儋州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','东方市');\">东方</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','定安县');\">定安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','德阳市');\">德阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','达州市');\">达州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','大理白族自治州');\">大理</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','德宏傣族景颇族自治州');\">德宏</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','迪庆藏族自治州');\">迪庆</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','定西市');\">定西</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>E</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','鄂尔多斯市');\">鄂尔多斯</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','鄂州市');\">鄂州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','恩施土家族苗族自治州');\">恩施</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>F</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','抚顺市');\">抚顺</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阜新市');\">阜新</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阜阳市');\">阜阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','福州市');\">福州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','抚州市');\">抚州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','佛山市');\">佛山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','防城港市');\">防城港</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>G</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','赣州市');\">赣州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','广州市');\">广州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','桂林市');\">桂林</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','贵港市');\">贵港</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','广元市');\">广元</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','广安市');\">广安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','甘孜藏族自治州');\">甘孜</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','贵阳市');\">贵阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','甘南藏族自治州');\">甘南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','果洛藏族自治州');\">果洛</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','固原市');\">固原</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>H</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','邯郸市');\">邯郸</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','衡水市');\">衡水</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','呼和浩特市');\">呼和浩特</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','呼伦贝尔市');\">呼伦贝尔</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','葫芦岛市');\">葫芦岛</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','哈尔滨市');\">哈尔滨</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','鹤岗市');\">鹤岗</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','黑河市');\">黑河</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','淮安市');\">淮安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','杭州市');\">杭州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','湖州市');\">湖州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','合肥市');\">合肥</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','淮南市');\">淮南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','淮北市');\">淮北</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','黄山市');\">黄山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','菏泽市');\">菏泽</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','鹤壁市');\">鹤壁</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','黄石市');\">黄石</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','黄冈市');\">黄冈</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','衡阳市');\">衡阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','怀化市');\">怀化</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','惠州市');\">惠州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','河源市');\">河源</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','贺州市');\">贺州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','河池市');\">河池</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','海口市');\">海口</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','红河哈尼族彝族自治州');\">红河</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','汉中市');\">汉中</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','海东地区');\">海东</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','海北藏族自治州');\">海北</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','黄南藏族自治州');\">黄南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','海南藏族自治州');\">海南州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','海西蒙古族藏族自治州');\">海西</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','哈密地区');\">哈密</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','和田地区');\">和田</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>J</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','晋城市');\">晋城</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','晋中市');\">晋中</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','锦州市');\">锦州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','吉林市');\">吉林</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','鸡西市');\">鸡西</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','佳木斯市');\">佳木斯</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','嘉兴市');\">嘉兴</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','金华市');\">金华</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','景德镇市');\">景德镇</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','九江市');\">九江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','吉安市');\">吉安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','济南市');\">济南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','济宁市');\">济宁</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','焦作市');\">焦作</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','荆门市');\">荆门</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','荆州市');\">荆州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','江门市');\">江门</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','揭阳市');\">揭阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','嘉峪关市');\">嘉峪关</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','金昌市');\">金昌</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','酒泉市');\">酒泉</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>K</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','开封市');\">开封</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','昆明市');\">昆明</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','克拉玛依市');\">克拉玛依</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','克孜勒苏柯尔克孜自治州');\">克孜勒苏</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','喀什地区');\">喀什</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>L</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','廊坊市');\">廊坊</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','临汾市');\">临汾</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','吕梁市');\">吕梁</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','辽阳市');\">辽阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','辽源市');\">辽源</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','连云港市');\">连云港</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','丽水市');\">丽水</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','六安市');\">六安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','龙岩市');\">龙岩</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','莱芜市');\">莱芜</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','临沂市');\">临沂</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','聊城市');\">聊城</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','洛阳市');\">洛阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','漯河市');\">漯河</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','娄底市');\">娄底</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','柳州市');\">柳州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','来宾市');\">来宾</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','临高县');\">临高</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','乐东黎族自治县');\">乐东</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','陵水黎族自治县');\">陵水</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','泸州市');\">泸州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','乐山市');\">乐山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','凉山彝族自治州');\">凉山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','六盘水市');\">六盘水</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','丽江市');\">丽江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','临沧市');\">临沧</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','拉萨市');\">拉萨</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','林芝地区');\">林芝</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','兰州市');\">兰州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','陇南市');\">陇南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','临夏回族自治州');\">临夏</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>M</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','牡丹江市');\">牡丹江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','马鞍山市');\">马鞍山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','茂名市');\">茂名</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','梅州市');\">梅州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','绵阳市');\">绵阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','眉山市');\">眉山</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>N</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','南京市');\">南京</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','南通市');\">南通</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宁波市');\">宁波</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','南平市');\">南平</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宁德市');\">宁德</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','南昌市');\">南昌</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','南阳市');\">南阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','南宁市');\">南宁</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','内江市');\">内江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','南充市');\">南充</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','怒江傈僳族自治州');\">怒江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','那曲地区');\">那曲</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>P</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','盘锦市');\">盘锦</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','莆田市');\">莆田</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','萍乡市');\">萍乡</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','平顶山市');\">平顶山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','濮阳市');\">濮阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','攀枝花市');\">攀枝花</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','普洱市');\">普洱</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','平凉市');\">平凉</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>Q</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','秦皇岛市');\">秦皇岛</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','齐齐哈尔市');\">齐齐哈尔</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','七台河市');\">七台河</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','衢州市');\">衢州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','泉州市');\">泉州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','青岛市');\">青岛</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','潜江市');\">潜江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','清远市');\">清远</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','钦州市');\">钦州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','琼海市');\">琼海</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','琼中黎族苗族自治县');\">琼中</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','黔西南布依族苗族自治州');\">黔西南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','黔东南苗族侗族自治州');\">黔东南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','黔南布依族苗族自治州');\">黔南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','曲靖市');\">曲靖</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','庆阳市');\">庆阳</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>R</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','日照市');\">日照</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','日喀则地区');\">日喀则</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>S</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','石家庄市');\">石家庄</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','朔州市');\">朔州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','沈阳市');\">沈阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','四平市');\">四平</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','松原市');\">松原</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','双鸭山市');\">双鸭山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','绥化市');\">绥化</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','上海市');\">上海</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','苏州市');\">苏州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','绍兴市');\">绍兴</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','三明市');\">三明</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','上饶市');\">上饶</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','三门峡市');\">三门峡</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','商丘市');\">商丘</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','十堰市');\">十堰</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宿迁市');\">宿迁</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宿州市');\">宿州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','随州市');\">随州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','邵阳市');\">邵阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','韶关市');\">韶关</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','深圳市');\">深圳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','汕头市');\">汕头</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','汕尾市');\">汕尾</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','三亚市');\">三亚</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','遂宁市');\">遂宁</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','山南地区');\">山南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','商洛市');\">商洛</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','石嘴山市');\">石嘴山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','石河子市');\">石河子</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>T</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','天津市');\">天津</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','唐山市');\">唐山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','太原市');\">太原</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','通辽市');\">通辽</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','铁岭市');\">铁岭</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','通化市');\">通化</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','泰州市');\">泰州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','台州市');\">台州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','铜陵市');\">铜陵</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','泰安市');\">泰安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','天门市');\">天门</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','屯昌县');\">屯昌</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','铜川市');\">铜川</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','天水市');\">天水</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','吐鲁番地区');\">吐鲁番</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','塔城地区');\">塔城</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','图木舒克市');\">图木舒克</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>W</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','乌海市');\">乌海</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','乌兰察布市');\">乌兰察布</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','无锡市');\">无锡</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','温州市');\">温州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','芜湖市');\">芜湖</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','潍坊市');\">潍坊</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','威海市');\">威海</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','武汉市');\">武汉</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','梧州市');\">梧州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','五指山市');\">五指山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','文昌市');\">文昌</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','万宁市');\">万宁</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','文山壮族苗族自治州');\">文山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','渭南市');\">渭南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','武威市');\">武威</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','吴忠市');\">吴忠</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','乌鲁木齐市');\">乌鲁木齐</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','五家渠市');\">五家渠</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>X</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','邢台市');\">邢台</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','忻州市');\">忻州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','兴安盟');\">兴安盟</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','锡林郭勒盟');\">锡林郭勒</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','徐州市');\">徐州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宣城市');\">宣城</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','厦门市');\">厦门</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','新余市');\">新余</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','新乡市');\">新乡</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','许昌市');\">许昌</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','信阳市');\">信阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','襄樊市');\">襄樊</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','孝感市');\">孝感</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','咸宁市');\">咸宁</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','仙桃市');\">仙桃</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','湘潭市');\">湘潭</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','湘西土家族苗族自治州');\">湘西</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','西双版纳傣族自治州');\">西双版纳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','西安市');\">西安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','咸阳市');\">咸阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','西宁市');\">西宁</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>Y</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阳泉市');\">阳泉</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','运城市');\">运城</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','营口市');\">营口</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','延边朝鲜族自治州');\">延边</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','伊春市');\">伊春</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','盐城市');\">盐城</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','扬州市');\">扬州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','鹰潭市');\">鹰潭</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宜春市');\">宜春</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','烟台市');\">烟台</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宜昌市');\">宜昌</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','岳阳市');\">岳阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','益阳市');\">益阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','永州市');\">永州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阳江市');\">阳江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','云浮市');\">云浮</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','玉林市');\">玉林</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宜宾市');\">宜宾</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','雅安市');\">雅安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','玉溪市');\">玉溪</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','延安市');\">延安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','榆林市');\">榆林</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','玉树藏族自治州');\">玉树</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','银川市');\">银川</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','伊犁哈萨克自治州');\">伊犁</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>Z</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','张家口市');\">张家口</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','镇江市');\">镇江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','舟山市');\">舟山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','漳州市');\">漳州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','淄博市');\">淄博</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','枣庄市');\">枣庄</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','郑州市');\">郑州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','周口市');\">周口</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','驻马店市');\">驻马店</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','株洲市');\">株洲</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','张家界市');\">张家界</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','珠海市');\">珠海</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','湛江市');\">湛江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','肇庆市');\">肇庆</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','中山市');\">中山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','自贡市');\">自贡</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','资阳市');\">资阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','遵义市');\">遵义</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','昭通市');\">昭通</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','张掖市');\">张掖</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','中卫市');\">中卫</a>";
	strHtml += "</td></tr>\r\n";

	strHtml += "</table></div>\r\n"
	g_CityDiv.innerHTML = strHtml;
}

function showCityDiv_(strTxtID)
{
	var txtInputPos = getInputBoxPos(strTxtID);

	g_CityDiv = document.createElement("DIV");
	g_CityDiv.id = "cityDiv";
	g_CityDiv.style.borderRight="black 1px solid";
	g_CityDiv.style.borderLeft="black 1px solid";
	g_CityDiv.style.borderTop="black 1px solid";
	g_CityDiv.style.borderBottom="black 1px solid";
	g_CityDiv.style.zIndex="100";
	g_CityDiv.style.paddingRight="0px";
	g_CityDiv.style.paddingLeft="5px";
	g_CityDiv.style.paddingTop="5px";
	g_CityDiv.style.paddingBottom="5px";
	g_CityDiv.style.display="block";
	g_CityDiv.style.position="absolute";
	g_CityDiv.style.backgroundColor="#ffffff";
	
	g_CityDiv.style.left=txtInputPos[0] + "px";
	g_CityDiv.style.top=txtInputPos[1] + txtInputPos[3] + "px";
	//alert(g_CityDiv.style.top);
	createCityDIVHtml_(strTxtID);
	document.body.appendChild(g_CityDiv);
}

function createCityDIVHtml_(strTxtID)
{
	var strHtml = "<iframe style=\"position:absolute;z-index:-1;width:200px;height:300px;\" frameborder=\"0\"></iframe><div style=\"overflow:auto;width:200px;height:300px;\"><table width=\"395\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"  bgcolor=\"#FFFFFF\" class=\"right_box\" style=\"padding:0 10px;\" >\r\n";
	strHtml += "<tr><td width=\"360\" height=\"27\" class=\"t_b\"><strong>省市列表</strong></td>";
	strHtml += "<td width=\"38\" align=\"right\" valign=\"middle\" class=\"t_b\"><a onclick=\"noCityDiv();\"><img src=\"../images/closebtn.gif\" width=\"11\" height=\"11\" border=\"0\" /></a></td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\">全国</span>(以下含34个省、自治区、直辖市、特别行政区，340个地级市；拼音排序) </td></tr>\r\n";
	//下面的就是真正的全国的内容了 
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>A</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阿拉善盟');\">阿拉善</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','鞍山市');\">鞍山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','安庆市');\">安庆</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','安阳市');\">安阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阿坝藏族羌族自治州');\">阿坝</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','安顺市');\">安顺</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阿里地区');\">阿里</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','安康市');\">安康</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阿克苏地区');\">阿克苏</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阿勒泰地区');\">阿勒泰</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阿拉尔市');\">阿拉尔</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','澳门特别行政区');\">澳门</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>B</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','北京市');\">北京</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','保定市');\">保定</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','包头市');\">包头</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','本溪市');\">本溪</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','白山市');\">白山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','白城市');\">白城</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','蚌埠市');\">蚌埠</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','亳州市');\">亳州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','滨州市');\">滨州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','北海市');\">北海</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','百色市');\">百色</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','白沙黎族自治县');\">白沙</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','保亭黎族苗族自治县');\">保亭</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','巴中市');\">巴中</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','毕节地区');\">毕节</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','保山市');\">保山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宝鸡市');\">宝鸡</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','白银市');\">白银</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','博尔塔拉蒙古自治州');\">博尔塔拉</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','巴音郭楞蒙古自治州');\">巴音郭楞</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>C</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','承德市');\">承德</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','沧州市');\">沧州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','长治市');\">长治</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','赤峰市');\">赤峰</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','朝阳市');\">朝阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','长春市');\">长春</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','常州市');\">常州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','滁州市');\">滁州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','巢湖市');\">巢湖</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','池州市');\">池州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','长沙市');\">长沙</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','常德市');\">常德</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','郴州市');\">郴州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','潮州市');\">潮州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','崇左市');\">崇左</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','澄迈县');\">澄迈</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','昌江黎族自治县');\">昌江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','重庆市');\">重庆</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','成都市');\">成都</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','楚雄彝族自治州');\">楚雄</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','昌都地区');\">昌都</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','昌吉回族自治州');\">昌吉</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>D</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','大同市');\">大同</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','大连市');\">大连</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','丹东市');\">丹东</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','大庆市');\">大庆</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','大兴安岭地区');\">大兴安岭</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','东营市');\">东营</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','德州市');\">德州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','东莞市');\">东莞</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','儋州市');\">儋州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','东方市');\">东方</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','定安县');\">定安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','德阳市');\">德阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','达州市');\">达州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','大理白族自治州');\">大理</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','德宏傣族景颇族自治州');\">德宏</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','迪庆藏族自治州');\">迪庆</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','定西市');\">定西</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>E</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','鄂尔多斯市');\">鄂尔多斯</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','鄂州市');\">鄂州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','恩施土家族苗族自治州');\">恩施</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>F</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','抚顺市');\">抚顺</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阜新市');\">阜新</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阜阳市');\">阜阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','福州市');\">福州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','抚州市');\">抚州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','佛山市');\">佛山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','防城港市');\">防城港</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>G</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','赣州市');\">赣州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','广州市');\">广州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','桂林市');\">桂林</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','贵港市');\">贵港</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','广元市');\">广元</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','广安市');\">广安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','甘孜藏族自治州');\">甘孜</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','贵阳市');\">贵阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','甘南藏族自治州');\">甘南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','果洛藏族自治州');\">果洛</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','固原市');\">固原</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>H</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','邯郸市');\">邯郸</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','衡水市');\">衡水</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','呼和浩特市');\">呼和浩特</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','呼伦贝尔市');\">呼伦贝尔</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','葫芦岛市');\">葫芦岛</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','哈尔滨市');\">哈尔滨</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','鹤岗市');\">鹤岗</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','黑河市');\">黑河</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','淮安市');\">淮安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','杭州市');\">杭州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','湖州市');\">湖州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','合肥市');\">合肥</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','淮南市');\">淮南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','淮北市');\">淮北</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','黄山市');\">黄山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','菏泽市');\">菏泽</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','鹤壁市');\">鹤壁</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','黄石市');\">黄石</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','黄冈市');\">黄冈</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','衡阳市');\">衡阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','怀化市');\">怀化</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','惠州市');\">惠州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','河源市');\">河源</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','贺州市');\">贺州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','河池市');\">河池</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','海口市');\">海口</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','红河哈尼族彝族自治州');\">红河</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','汉中市');\">汉中</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','海东地区');\">海东</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','海北藏族自治州');\">海北</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','黄南藏族自治州');\">黄南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','海南藏族自治州');\">海南州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','海西蒙古族藏族自治州');\">海西</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','哈密地区');\">哈密</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','和田地区');\">和田</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>J</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','晋城市');\">晋城</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','晋中市');\">晋中</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','锦州市');\">锦州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','吉林市');\">吉林</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','鸡西市');\">鸡西</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','佳木斯市');\">佳木斯</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','嘉兴市');\">嘉兴</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','金华市');\">金华</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','景德镇市');\">景德镇</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','九江市');\">九江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','吉安市');\">吉安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','济南市');\">济南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','济宁市');\">济宁</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','焦作市');\">焦作</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','荆门市');\">荆门</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','荆州市');\">荆州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','江门市');\">江门</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','揭阳市');\">揭阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','嘉峪关市');\">嘉峪关</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','金昌市');\">金昌</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','酒泉市');\">酒泉</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>K</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','开封市');\">开封</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','昆明市');\">昆明</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','克拉玛依市');\">克拉玛依</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','克孜勒苏柯尔克孜自治州');\">克孜勒苏</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','喀什地区');\">喀什</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>L</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','廊坊市');\">廊坊</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','临汾市');\">临汾</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','吕梁市');\">吕梁</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','辽阳市');\">辽阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','辽源市');\">辽源</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','连云港市');\">连云港</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','丽水市');\">丽水</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','六安市');\">六安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','龙岩市');\">龙岩</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','莱芜市');\">莱芜</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','临沂市');\">临沂</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','聊城市');\">聊城</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','洛阳市');\">洛阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','漯河市');\">漯河</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','娄底市');\">娄底</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','柳州市');\">柳州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','来宾市');\">来宾</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','临高县');\">临高</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','乐东黎族自治县');\">乐东</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','陵水黎族自治县');\">陵水</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','泸州市');\">泸州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','乐山市');\">乐山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','凉山彝族自治州');\">凉山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','六盘水市');\">六盘水</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','丽江市');\">丽江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','临沧市');\">临沧</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','拉萨市');\">拉萨</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','林芝地区');\">林芝</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','兰州市');\">兰州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','陇南市');\">陇南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','临夏回族自治州');\">临夏</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>M</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','牡丹江市');\">牡丹江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','马鞍山市');\">马鞍山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','茂名市');\">茂名</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','梅州市');\">梅州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','绵阳市');\">绵阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','眉山市');\">眉山</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>N</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','南京市');\">南京</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','南通市');\">南通</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宁波市');\">宁波</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','南平市');\">南平</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宁德市');\">宁德</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','南昌市');\">南昌</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','南阳市');\">南阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','南宁市');\">南宁</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','内江市');\">内江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','南充市');\">南充</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','怒江傈僳族自治州');\">怒江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','那曲地区');\">那曲</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>P</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','盘锦市');\">盘锦</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','莆田市');\">莆田</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','萍乡市');\">萍乡</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','平顶山市');\">平顶山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','濮阳市');\">濮阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','攀枝花市');\">攀枝花</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','普洱市');\">普洱</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','平凉市');\">平凉</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>Q</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','秦皇岛市');\">秦皇岛</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','齐齐哈尔市');\">齐齐哈尔</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','七台河市');\">七台河</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','衢州市');\">衢州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','泉州市');\">泉州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','青岛市');\">青岛</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','潜江市');\">潜江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','清远市');\">清远</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','钦州市');\">钦州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','琼海市');\">琼海</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','琼中黎族苗族自治县');\">琼中</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','黔西南布依族苗族自治州');\">黔西南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','黔东南苗族侗族自治州');\">黔东南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','黔南布依族苗族自治州');\">黔南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','曲靖市');\">曲靖</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','庆阳市');\">庆阳</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>R</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','日照市');\">日照</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','日喀则地区');\">日喀则</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>S</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','石家庄市');\">石家庄</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','朔州市');\">朔州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','沈阳市');\">沈阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','四平市');\">四平</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','松原市');\">松原</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','双鸭山市');\">双鸭山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','绥化市');\">绥化</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','上海市');\">上海</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','苏州市');\">苏州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','绍兴市');\">绍兴</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','三明市');\">三明</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','上饶市');\">上饶</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','三门峡市');\">三门峡</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','商丘市');\">商丘</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','十堰市');\">十堰</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宿迁市');\">宿迁</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宿州市');\">宿州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','随州市');\">随州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','邵阳市');\">邵阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','韶关市');\">韶关</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','深圳市');\">深圳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','汕头市');\">汕头</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','汕尾市');\">汕尾</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','三亚市');\">三亚</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','遂宁市');\">遂宁</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','山南地区');\">山南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','商洛市');\">商洛</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','石嘴山市');\">石嘴山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','石河子市');\">石河子</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>T</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','天津市');\">天津</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','唐山市');\">唐山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','太原市');\">太原</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','通辽市');\">通辽</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','铁岭市');\">铁岭</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','通化市');\">通化</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','泰州市');\">泰州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','台州市');\">台州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','铜陵市');\">铜陵</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','泰安市');\">泰安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','天门市');\">天门</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','屯昌县');\">屯昌</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','铜川市');\">铜川</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','天水市');\">天水</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','吐鲁番地区');\">吐鲁番</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','塔城地区');\">塔城</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','图木舒克市');\">图木舒克</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>W</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','乌海市');\">乌海</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','乌兰察布市');\">乌兰察布</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','无锡市');\">无锡</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','温州市');\">温州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','芜湖市');\">芜湖</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','潍坊市');\">潍坊</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','威海市');\">威海</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','武汉市');\">武汉</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','梧州市');\">梧州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','五指山市');\">五指山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','文昌市');\">文昌</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','万宁市');\">万宁</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','文山壮族苗族自治州');\">文山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','渭南市');\">渭南</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','武威市');\">武威</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','吴忠市');\">吴忠</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','乌鲁木齐市');\">乌鲁木齐</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','五家渠市');\">五家渠</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>X</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','邢台市');\">邢台</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','忻州市');\">忻州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','兴安盟');\">兴安盟</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','锡林郭勒盟');\">锡林郭勒</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','徐州市');\">徐州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宣城市');\">宣城</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','厦门市');\">厦门</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','新余市');\">新余</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','新乡市');\">新乡</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','许昌市');\">许昌</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','信阳市');\">信阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','襄樊市');\">襄樊</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','孝感市');\">孝感</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','咸宁市');\">咸宁</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','仙桃市');\">仙桃</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','湘潭市');\">湘潭</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','湘西土家族苗族自治州');\">湘西</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','西双版纳傣族自治州');\">西双版纳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','西安市');\">西安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','咸阳市');\">咸阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','西宁市');\">西宁</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>Y</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阳泉市');\">阳泉</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','运城市');\">运城</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','营口市');\">营口</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','延边朝鲜族自治州');\">延边</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','伊春市');\">伊春</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','盐城市');\">盐城</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','扬州市');\">扬州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','鹰潭市');\">鹰潭</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宜春市');\">宜春</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','烟台市');\">烟台</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宜昌市');\">宜昌</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','岳阳市');\">岳阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','益阳市');\">益阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','永州市');\">永州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','阳江市');\">阳江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','云浮市');\">云浮</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','玉林市');\">玉林</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','宜宾市');\">宜宾</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','雅安市');\">雅安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','玉溪市');\">玉溪</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','延安市');\">延安</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','榆林市');\">榆林</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','玉树藏族自治州');\">玉树</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','银川市');\">银川</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','伊犁哈萨克自治州');\">伊犁</a>";
	strHtml += "</td></tr>\r\n";
	strHtml += "<tr bgcolor=\"#FFFFFF\">\r\n";
	strHtml += "<td height=\"25\" colspan=\"2\"><span class=\"wz\"><strong>Z</strong></span>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','张家口市');\">张家口</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','镇江市');\">镇江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','舟山市');\">舟山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','漳州市');\">漳州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','淄博市');\">淄博</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','枣庄市');\">枣庄</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','郑州市');\">郑州</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','周口市');\">周口</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','驻马店市');\">驻马店</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','株洲市');\">株洲</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','张家界市');\">张家界</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','珠海市');\">珠海</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','湛江市');\">湛江</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','肇庆市');\">肇庆</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','中山市');\">中山</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','自贡市');\">自贡</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','资阳市');\">资阳</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','遵义市');\">遵义</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','昭通市');\">昭通</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','张掖市');\">张掖</a>";
	strHtml += " <a href=\"#\" class=\"wz\" onclick=\"setInputValue('" + strTxtID + "','中卫市');\">中卫</a>";
	strHtml += "</td></tr>\r\n";

	strHtml += "</table></div>\r\n"
	g_CityDiv.innerHTML = strHtml;
}